# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPpp():
  def setup_method(self, method):
    capabilities = {
    "name" : "TEST",
    "browserName": "chrome",
    "browserVersion": "114.0",
    "selenoid:options": {"name": "test_DR",
        "enableVideo": False
        ,"enableVNC": True
      }
   }
    self.driver = webdriver.Remote(command_executor='http://localhost:4444', desired_capabilities=capabilities)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_ppp(self):
    # Test name: ppp
    self.driver.get("https://demo.lumpsum.in.th/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".mosh-btn-policy").click()
    self.driver.find_element(By.ID, "moshDropdown").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2) > .notification").click()
    self.vars["win1664"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1664"])
    self.driver.find_element(By.CSS_SELECTOR, ".btn-refinance-topshelf-select-tcr").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-refinance-topshelf-select-kkp").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-refinance-topshelf-select-kkp")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "body")))
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-next-or")
    actions = ActionChains(self.driver)
    #actions.move_to_element(element).perform()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn-next-or")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-next-or").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "firstname")))
    self.driver.find_element(By.ID, "firstname").click()
    self.driver.find_element(By.ID, "firstname").send_keys("pp")
    self.driver.find_element(By.ID, "lastname").click()
    self.driver.find_element(By.ID, "lastname").send_keys("aa")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("gss@gmau.com")
    self.driver.find_element(By.ID, "mobile_number").click()
    self.driver.find_element(By.ID, "mobile_number").send_keys("0009222221")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "btn_req_otp_mobile")))
    element = self.driver.find_element(By.ID, "btn_req_otp_mobile")
    actions = ActionChains(self.driver)
    #actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "btn_req_otp_mobile").click()
    #element = self.driver.find_element(By.CSS_SELECTOR, "body")
    #actions = ActionChains(self.driver)
    #actions.move_to_element(element, 0, 0).perform()
    #WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.ID, "OTP")))
    self.driver.find_element(By.ID, "OTP").send_keys("111111")
    #self.driver.find_element(By.CSS_SELECTOR, ".connect-btn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.ID, "btn_req_otp_mobile")))
    self.driver.find_element(By.ID, "income_per_month").click()
    self.driver.find_element(By.ID, "income_per_month").send_keys("100,000")
    self.driver.find_element(By.ID, "career_id").click()
    dropdown = self.driver.find_element(By.ID, "career_id")
    dropdown.find_element(By.XPATH, "//option[. = 'พนักงานบริษัท']").click()
    self.driver.find_element(By.ID, "homestead_type_id").click()
    dropdown = self.driver.find_element(By.ID, "homestead_type_id")
    dropdown.find_element(By.XPATH, "//option[. = 'บ้าน (บ้านเดี่ยว, บ้านแฝด, ทาวน์เฮาส์, ทาวน์โฮม)']").click()
    self.driver.find_element(By.ID, "province").click()
    dropdown = self.driver.find_element(By.ID, "province")
    dropdown.find_element(By.XPATH, "//option[. = 'กรุงเทพมหานคร']").click()
    self.driver.find_element(By.ID, "home_balance").click()
    self.driver.find_element(By.ID, "home_balance").send_keys("1,000,000")
    self.driver.find_element(By.ID, "priority").click()
    dropdown = self.driver.find_element(By.ID, "priority")
    dropdown.find_element(By.XPATH, "//option[. = 'ดอกเบี้ยต่ำ']").click()
    self.driver.find_element(By.ID, "currently_paying_bank").click()
    dropdown = self.driver.find_element(By.ID, "currently_paying_bank")
    dropdown.find_element(By.XPATH, "//option[. = 'ธนาคารกรุงไทย']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "is_allowner")))
    self.driver.find_element(By.ID, "is_allowner").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "chk_form")))
    self.driver.find_element(By.ID, "chk_form").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "is_policy")))
    self.driver.find_element(By.ID, "is_policy").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "chk_form")))
    self.driver.find_element(By.ID, "chk_form").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".a:nth-child(4)")))
    self.driver.find_element(By.CSS_SELECTOR, ".a:nth-child(4)").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "next-desktop")))
    self.driver.find_element(By.ID, "next-desktop").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "save_refinance")))
    self.driver.find_element(By.ID, "save_refinance").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "span")))
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
  
