# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("https://www.google.co.th/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.ID, "APjFqb").send_keys("google chrome")
    self.driver.find_element(By.NAME, "btnK").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".fdYsqf > .CCgQ5 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "searchform").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".gb_h > path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "APjFqb").send_keys("facebook")
    self.driver.find_element(By.CSS_SELECTOR, ".zgAlFc svg").click()
    self.driver.find_element(By.ID, "gsr").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".jfN4p")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "APjFqb").send_keys("youtube")
    self.driver.find_element(By.CSS_SELECTOR, ".zgAlFc svg").click()
  
