# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlomsom():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testlomsom(self):
    self.driver.get("https://uat.lumpsum.in.th/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.ID, "moshDropdown").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2) > .notification").click()
    self.vars["win1688"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win1688"])
    self.driver.find_element(By.CSS_SELECTOR, ".btn > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_ipt_GSB-R0001").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_ipt_KKP-R0001").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_ipt_TCR-R0001").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_ipt_TCR-R0001")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn > img").click()
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
  
